# install: conda env create -f environment-win.yaml
# update:  conda env update -f environment-win.yaml
name: vame
channels:
  - pytorch
  - nvidia
  - defaults
channel_priority: strict
dependencies:
  - python=3.11
  - cudatoolkit=11.8
  - pytorch=2.5.1
  - pip
  - pip:
      - .
