name: Build, Deploy to GitHub Pages and Deploy PR Preview

on:
  push:
    branches: 
      - docs/adding-docs-app
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

permissions:
  contents: write
  pages: write
  pull-requests: write

concurrency: ci-${{ github.ref }}

jobs:
  build-deploy-and-preview:
    name: Build, Deploy to GitHub Pages and Deploy PR Preview
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Install docs dependencies.
        run: pip install -r docs/requirements-docs.txt
      - name: Auto generate API Reference.
        run: cd docs && pydoc-markdown
      - name: Build, Deploy to GitHub Pages and Deploy PR Preview
        uses: chvmvd/build-deploy-and-preview-action@v1.2.0
        with:
          type: docusaurus