name: Deploy VAME Docs to GitHub Pages

on:
  push:
    branches:
      - docs

jobs:
  deploy:
    name: Deploy VAME Docs to GitHub Pages
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install docs dependencies.
        run: pip install -r docs/requirements-docs.txt

      - name: Auto generate API Reference.
        run: cd docs && pydoc-markdown

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
          working-directory: docs/vame-docs-app
          cache-dependency-path: docs/vame-docs-app/yarn.lock

      - name: Install dependencies
        run: cd docs/vame-docs-app && yarn install --frozen-lockfile
      - name: Build website
        run: cd docs/vame-docs-app && yarn build

      # Popular action to deploy to GitHub Pages:
      # Docs: https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-docusaurus
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/vame-docs-app/build
