name: Upload Package to PyPI on release

on:
  release:
    types: [published]

jobs:
  pypi-release:
    name: Release VAME in pypi
    runs-on: ubuntu-latest
    needs: github-release
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build
          pip install twine
      - name: Build and publish to PyPI
        run: |
          python -m build
          twine upload dist/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}